[package]
name = "tayga-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clickhouse.workspace = true
hex.workspace = true
serde.workspace = true
tayga-model.workspace = true
tracing.workspace = true
xxhash-rust.workspace = true

[dev-dependencies]
criterion.workspace = true
flate2.workspace = true
rand.workspace = true
tokio.workspace = true

[[bench]]
name = "flatten"
harness = false
